Repository Kernel360/KDEV4-SODA-FE, pull requests merged in 2025-05, with the labels that each got.

#195 [Fix] 재승인요청에서 부모요청 버튼 눌렀을 때 이동되게 수정
  src/pages/user/projects/RequestDetail.tsx
Labels: 🐞 Bugfix

#197 [Fix] 데이터로그 액션이 수정인데 diff가 null이거나 비었을 때 처리로직 추가
  .tsconfig.tsbuildinfo
  src/pages/admin/DataManagement.tsx
  src/pages/admin/projects/Project.tsx
Labels: 🐞 Bugfix

#199 [Design] 전반적인 디자인 개선
  .tsconfig.tsbuildinfo
  src/pages/admin/AdminMain.tsx
  src/pages/admin/projects/ProjectList.tsx
  src/pages/user/UserProjectDetail.tsx
Labels: 🔧 Refactor

#202 [Fix] 프로젝트 관련 오류 해결
  .tsconfig.tsbuildinfo
  src/components/articles/ArticleForm.tsx
  src/components/projects/CreateProjectSteps.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/admin/projects/ProjectList.tsx
  src/pages/article/CreateArticle.tsx
  src/pages/article/EditArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/pages/auth/Login.tsx
  src/types/article.ts
Labels: 🐞 Bugfix

#206 [Docs] README 작성
  README.md
Labels: 📃 Docs

#210 [Fix] 게시글 API 연동 오류 해결
  src/pages/article/EditArticle.tsx
  src/services/projectService.ts
Labels: 🐞 Bugfix

#212 [Feat] presignedUrl 업로드 시 ACL 읽기 설정 추가
  src/components/layout/Header.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/auth/Login.tsx
  src/pages/user/projects/CreateRequest.tsx
Labels: 🐞 Bugfix

#213 [Release] develop to main
  src/components/layout/Header.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/article/EditArticle.tsx
  src/pages/auth/Login.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/services/projectService.ts
Labels: 🤖 CI/CD

#217 [Release] Develop to Main
  src/pages/user/projects/CreateRequest.tsx
Labels: 🤖 CI/CD

#218 [Fix] amz설정 주석처리가 아니라 아예 삭제
  src/pages/user/projects/CreateRequest.tsx
Labels: 🐞 Bugfix

#222 [Release] Develop to Main
  .tsconfig.tsbuildinfo
  package-lock.json
  package.json
  src/App.tsx
  src/api/admin.ts
  src/api/api.ts
  src/api/auth.ts
  src/api/client.ts
  src/api/company.ts
  src/api/task.ts
  src/components/accounts/AccountDetailForm.tsx
  src/components/articles/ArticleForm.tsx
  src/components/common/CompanyForm.tsx
  src/components/common/DataTable.tsx
  src/components/company/CompanyDetail.tsx
  src/components/modals/CompanySearchModal.tsx
  src/components/projects/CreateProjectSteps.tsx
  src/components/projects/PaymentManagement.tsx
  src/components/projects/ProjectArticle.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/lib/utils.ts
  src/pages/admin/AdminMain.tsx
  src/pages/admin/accounts/AccountDetail.tsx
  src/pages/admin/accounts/AccountList.tsx
  src/pages/admin/accounts/CreateAccount.tsx
  src/pages/admin/companies/Company.tsx
  src/pages/admin/companies/CompanyList.tsx
  src/pages/admin/companies/CreateCompany.tsx
  src/pages/admin/companies/EditCompany.tsx
  src/pages/admin/projects/CreateProject.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/admin/projects/ProjectCreate.tsx
  src/pages/admin/projects/ProjectList.tsx
  src/pages/article/Article.tsx
  src/pages/user/mypage/MyPage.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/services/companyService.ts
  src/types/api.ts
  src/types/company.ts
  src/utils/validation.ts
Labels: 🤖 CI/CD

#224 [Design] 관리자 대시보드, 사용자 대시보드 모바일 반응형 적용
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/UserSidebar.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/user/UserDashboard.tsx
Labels: ✨ Feature

#227 [Design] 대시보드 디자인 오류 수정 및 createdAt 한국 시간으로 설정
  src/components/comments/CommentSection.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/article/Article.tsx
  src/pages/user/UserDashboard.tsx
  src/pages/user/UserRequests.tsx
  src/pages/user/projects/RequestDetail.tsx
Labels: ✨ Feature

#228 [Release] Develop to Main
  src/components/comments/CommentSection.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/article/Article.tsx
  src/pages/user/UserDashboard.tsx
  src/pages/user/UserRequests.tsx
  src/pages/user/projects/RequestDetail.tsx
Labels: 🤖 CI/CD

#230 [Release] Develop to Main
  src/pages/user/projects/CreateRequest.tsx
Labels: 🤖 CI/CD

#232 [Release] Develop to Main
  src/pages/auth/UserInfo.tsx
Labels: 🤖 CI/CD

#235 [Fix] 상세보기했을 때 데이터 보이게 분기문 삭제
  src/pages/admin/DataManagement.tsx
Labels: 🐞 Bugfix

#236 Develop to main
  src/pages/admin/DataManagement.tsx
Labels: 🤖 CI/CD
