Repository Kernel360/KDEV4-SODA-FE, pull requests merged in 2025-04, with the labels that each got.

#9 [Feature] 프로젝트 조회 API 연동
  package-lock.json
  package.json
  src/components/common/DataTable.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/projects/ProjectCard.tsx
  src/components/projects/ProjectHeader.tsx
  src/components/projects/ProjectStages.tsx
  src/components/projects/StageCard.tsx
  src/main.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/admin/projects/ProjectList.tsx
  src/pages/auth/Login.tsx
  src/pages/user/projects/UserProject.tsx
  src/services/projectService.ts
  src/stores/projectStore.ts
  src/types/project.ts
  src/types/stage.ts
  src/types/task.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature

#14 setting: build.sh 파일 추가
  build.sh
Labels: ⚙️ Setting

#16 [Feature] 게시글, 댓글, 프로젝트 API 연동
  package-lock.json
  src/components/article/ArticleForm.tsx
  src/components/articles/ArticleForm.tsx
  src/components/comments/CommentSection.tsx
  src/components/project/ProjectCard.tsx
  src/components/project/ProjectInfo.tsx
  src/components/projects/ProjectArticle.tsx
  src/main.css
  src/pages/admin/companies/CompanyList.tsx
  src/pages/admin/projects/CreateProject.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/article/Article.tsx
  src/pages/article/CreateArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/pages/user/projects/UserProject.tsx
  src/pages/user/projects/articles/CreateArticle.tsx
  src/services/commentService.ts
  src/services/companyService.ts
  src/services/projectService.ts
  src/types/article.ts
  src/types/comment.ts
  src/types/stage.ts
Labels: ✨ Feature

#18 [Fix] build 오류 해결
  src/components/calendar/SimpleCalendar.tsx
  src/components/projects/StageCard.tsx
  src/pages/admin/projects/Project.tsx
  src/services/projectService.ts
  src/types/project.ts
Labels: 🐞 Bugfix

#25 [Feature] 대시보드/사이드바 등 기타 API 연동
  package-lock.json
  package.json
  src/App.tsx
  src/components/articles/ArticleForm.tsx
  src/components/comments/CommentSection.tsx
  src/components/layout/Header.tsx
  src/components/layout/UserSidebar.tsx
  src/components/projects/ProjectCard.tsx
  src/components/projects/ProjectList.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/article/EditArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/pages/profile/MyPage.tsx
  src/pages/user/UserMain.tsx
  src/pages/user/UserProfile.tsx
  src/services/commentService.ts
  src/services/projectService.ts
  src/stores/userStore.ts
  src/types/article.ts
Labels: ✨ Feature

#27 [Feature] 기타 API 연동
  src/components/layout/UserSidebar.tsx
  src/components/projects/ProjectArticle.tsx
  src/types/article.ts
Labels: ✨ Feature

#31 [Fix] API 연동 시 발생한 빌드 오류 해결
  .tsconfig.tsbuildinfo
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/config.ts
  src/api/request.ts
  src/api/task.ts
  src/components/common/DataTable.tsx
  src/components/projects/ProjectCard.tsx
  src/components/projects/RequestForm.tsx
  src/components/projects/RequestList.tsx
  src/components/projects/StageCard.tsx
  src/components/projects/TaskRequestsModal.tsx
  src/components/request/RequestCard.tsx
  src/pages/admin/accounts/AccountList.tsx
  src/pages/user/UserMain.tsx
  src/services/commentService.ts
  src/services/projectService.ts
  src/types/request.ts
Labels: 🐞 Bugfix

#37 [Feature] 관리자/사용자 에 따른 header, sidebar 역할 분리
  .github/workflows/main.yml
  build.sh
  src/components/layout/Header.tsx
  src/components/layout/UserSidebar.tsx
Labels: ✨ Feature

#40 [Fix] vercel 새로고침 오류 해결
  src/components/layout/Header.tsx
  vercel.json
Labels: 🐞 Bugfix

#43 [Fix] request 반려 form 추가
  .tsconfig.tsbuildinfo
  src/components/projects/RequestDetail.tsx
  src/components/projects/RequestList.tsx
  src/components/projects/TaskRequestsModal.tsx
  src/components/tasks/Task.tsx
  src/pages/tasks/TaskDetailPage.tsx
  src/types/request.ts
Labels: 🐞 Bugfix

#45 [fix] 유효성 검사 추가
  .tsconfig.tsbuildinfo
  src/components/projects/CreateProjectForm.tsx
  src/services/projectService.ts
Labels: 🐞 Bugfix

#51 [Feature] 프로젝트 메인 페이지 수정
  src/App.tsx
  src/components/projects/AddStageModal.tsx
  src/components/projects/PaymentManagement.tsx
  src/components/projects/ProgressManagement.tsx
  src/components/projects/ProjectArticle.tsx
  src/components/projects/ProjectHeader.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/UserProject.tsx
  src/types/project.ts
Labels: ✨ Feature

#59 [Fix] project, article 오류 해결 (수정 API 제외)
  .tsconfig.tsbuildinfo
  src/components/articles/ArticleForm.tsx
  src/components/common/ProjectForm.tsx
  src/components/projects/ProjectArticle.tsx
  src/pages/admin/projects/EditProject.tsx
  src/pages/article/Article.tsx
  src/pages/article/CreateArticle.tsx
  src/pages/article/EditArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/services/projectService.ts
  src/types/project.ts
Labels: 🐞 Bugfix, ✨ Feature

#63 [Refactor] 사이드바 수정
  .tsconfig.tsbuildinfo
  src/App.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/components/layout/UserSidebar.tsx
  src/pages/auth/Login.tsx
  src/pages/user/ProjectList.tsx
  src/pages/user/Projects.tsx
  src/pages/user/RecentPosts.tsx
  src/pages/user/RequestList.tsx
  src/pages/user/projects/UserProjectList.tsx
  src/pages/user/projects/index.ts
  src/stores/userStore.ts
  src/types/project.ts
Labels: 🔧 Refactor

#68 [Feature] 승인요청 CRUD 구현
  .tsconfig.tsbuildinfo
  src/App.tsx
  src/api/api.ts
  src/api/auth.ts
  src/api/axios.ts
  src/api/config.ts
  src/api/user.ts
  src/components/projects/PaymentManagement.tsx
  src/components/projects/ProgressManagement.tsx
  src/components/projects/ProjectStages.tsx
  src/components/projects/RequestDetailModal.tsx
  src/pages/admin/accounts/CreateAccount.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/UserInfo.tsx
  src/pages/user/UserDashboard.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/RequestDetail.tsx
  src/services/commentService.ts
  src/services/projectService.ts
  src/stores/userStore.ts
  src/types/api.ts
  src/types/project.ts
Labels: ✨ Feature

#69 [Fix] 프로젝트/게시글 수정 오류 해결
  .tsconfig.tsbuildinfo
  package-lock.json
  package.json
  src/components/articles/ArticleForm.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/ProjectForm.tsx
  src/components/layout/Sidebar.tsx
  src/components/projects/CreateProjectForm.tsx
  src/pages/admin/projects/CreateProject.tsx
  src/pages/admin/projects/EditProject.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/article/Article.tsx
  src/pages/article/CreateArticle.tsx
  src/pages/article/EditArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/services/projectService.ts
  src/types/article.ts
Labels: 🐞 Bugfix

#72 [Fix] 단계별 요청수 제대로 출력되게 수정
  src/components/projects/PaymentManagement.tsx
Labels: 🐞 Bugfix

#77 [Refactor] 진척관리 삭제 및 결제 관리 로직 변경
  .tsconfig.tsbuildinfo
  src/components/projects/PaymentManagement.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/user/projects/RequestDetail.tsx
  src/pages/user/projects/UserProject.tsx
Labels: 🔧 Refactor

#96 [Feature] 승인권자 다중 지정/출력 기능 개발
  .tsconfig.tsbuildinfo
  src/api/axios.ts
  src/pages/admin/projects/Project.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/RequestDetail.tsx
  src/services/commentService.ts
  src/services/projectService.ts
  src/services/requestService.ts
  src/types/project.ts
Labels: ✨ Feature

#98 [Fix] Request에 승인중 상태 추가, Response에 status필드가 추가됨에 따라 FE 수정
  .tsconfig.tsbuildinfo
  src/components/projects/PaymentManagement.tsx
  src/pages/user/projects/RequestDetail.tsx
Labels: 🐞 Bugfix

#119 [Fix] 프로젝트 상세페이지에서 승인요청이 조회되지 않는 버그 해결
  .tsconfig.tsbuildinfo
  src/components/projects/PaymentManagement.tsx
Labels: 🐞 Bugfix

#125 [Feature] presigned Url 발급 받고 S3에 직접 파일 저장하고 백엔드에 확인 메세지 보내게 구현
  src/api/axios.ts
  src/api/config.ts
  src/components/articles/ArticleForm.tsx
  src/pages/article/EditArticle.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/RequestDetail.tsx
  src/services/commentService.ts
  src/services/projectService.ts
Labels: ✨ Feature

#126 [Feature] 프로젝트/게시글 검색 기능 추가 및 화면 오류 수정
  .tsconfig.tsbuildinfo
  package-lock.json
  package.json
  src/components/articles/ArticleForm.tsx
  src/components/projects/ProjectArticle.tsx
  src/components/projects/ProjectHeader.tsx
  src/pages/admin/accounts/AccountList.tsx
  src/pages/admin/projects/ProjectList.tsx
  src/pages/article/Article.tsx
  src/pages/article/CreateArticle.tsx
  src/pages/article/EditArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/pages/user/projects/UserProject.tsx
  src/services/projectService.ts
Labels: 🐞 Bugfix, ✨ Feature

#129 [fix] articleform 오류 수정
  .tsconfig.tsbuildinfo
  src/components/articles/ArticleForm.tsx
Labels: 🐞 Bugfix

#133 [Fix] 어드민 대시보드의 진행중인 프로젝트에서 대시보드 버튼을 눌렀을 때 프로젝트 상세 수정페이지로 넘어가는 버그 해결
  src/api/axios.ts
  src/api/config.ts
  src/pages/admin/AdminMain.tsx
  src/services/commentService.ts
  src/services/projectService.ts
Labels: 🐞 Bugfix

#134 [Feat] 유저 대시보드에서 최근 승인요청 목록 기능 구현
  src/pages/user/UserDashboard.tsx
Labels: ✨ Feature

#135 [Feat] 일반유저의 요청사항목록 페이징해서 출력하는 페이지 구현
  .tsconfig.tsbuildinfo
  src/App.tsx
  src/pages/user/UserRequests.tsx
Labels: ✨ Feature

#137 [Feat] 승인요청 검색기능 구현
  .tsconfig.tsbuildinfo
  src/components/projects/PaymentManagement.tsx
Labels: ✨ Feature

#138 [Feat] 로그 키워드 검색 API 연결
  .tsconfig.tsbuildinfo
  src/pages/admin/DataManagement.tsx
  src/services/logService.ts
  src/types/log.ts
Labels: ✨ Feature

#144 [Feat] 일반유저 요청사항 목록에 검색기능 구현
  .tsconfig.tsbuildinfo
  src/pages/admin/projects/Project.tsx
  src/pages/user/UserRequests.tsx
Labels: ✨ Feature

#146 [Feature] 관리자 대시보드 - 단계별 프로젝트 조회
  .tsconfig.tsbuildinfo
  src/pages/admin/AdminMain.tsx
  src/services/api.ts
  src/services/client.ts
Labels: ✨ Feature

#148 [Feat] 최근 활동이 많은 프로젝트 API 연결
  .tsconfig.tsbuildinfo
  src/pages/admin/AdminMain.tsx
Labels: ✨ Feature

#149 [Feature] 질문사항 더미데이터 수정
  .tsconfig.tsbuildinfo
  src/App.tsx
  src/components/layout/UserSidebar.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/user/MyArticles.tsx
  src/pages/user/RecentPosts.tsx
  src/pages/user/UserDashboard.tsx
Labels: ✨ Feature

#150 [Fix] 프로젝트 관련 오류 해결
  .tsconfig.tsbuildinfo
  index.html
  public/logo.png
  public/vite.svg
  src/pages/admin/AdminMain.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/admin/projects/ProjectList.tsx
  src/services/projectService.ts
Labels: 🐞 Bugfix

#153 [Design] 디자인 수정
  .tsconfig.tsbuildinfo
  src/components/common/FormDatePicker.tsx
  src/components/common/FormSelect.tsx
  src/components/common/FormTextField.tsx
  src/components/projects/ProjectArticle.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/article/Article.tsx
  src/pages/article/EditArticle.tsx
  src/pages/article/ReplyArticle.tsx
  src/services/articleService.ts
  src/services/projectService.ts
  src/types/article.ts
Labels: 🐞 Bugfix

#155 [Feature] 유저 대시보드 수정
  .tsconfig.tsbuildinfo
  src/App.tsx
  src/components/auth/PrivateRoute.tsx
  src/components/layout/UserSidebar.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/user/ProjectList.tsx
  src/pages/user/Projects.tsx
  src/pages/user/UserDashboard.tsx
  src/pages/user/projects/UserProject.tsx
  src/services/projectService.ts
  src/types/project.ts
Labels: ✨ Feature

#157 [Feature] 더미데이터 수정 및 디자인 변경
  .tsconfig.tsbuildinfo
  src/components/comments/CommentSection.tsx
  src/components/projects/ProjectArticle.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/article/Article.tsx
  src/services/projectService.ts
  src/types/article.ts
Labels: ✨ Feature

#160 [Fix] 게시글 대댓글 오류 해결
  src/components/comments/CommentSection.tsx
Labels: 🐞 Bugfix

#167 [Feat] 승인요청 삭제버튼 복구
  .tsconfig.tsbuildinfo
  src/components/projects/PaymentManagement.tsx
  src/components/projects/ProjectArticle.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/RequestDetail.tsx
Labels: ✨ Feature

#168 [Feat] 승인권자 지정시 멤버 상태(자리비움 등) 보이게하는 기능 구현
  .tsconfig.tsbuildinfo
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/ReapplyRequest.tsx
  src/types/project.ts
Labels: ✨ Feature

#172 [Feature] 프로젝트/회사 생성 통계 API 연동
  package-lock.json
  package.json
  src/components/charts/CompanyCreationTrendChart.tsx
  src/components/charts/ProjectCreationTrendChart.tsx
  src/pages/admin/AdminMain.tsx
  src/pages/user/UserMain.tsx
  src/services/projectService.ts
Labels: ✨ Feature

#174 [Refact] 승인요청 각종 버튼 권한별 노출을 달리함
  .tsconfig.tsbuildinfo
  src/components/projects/PaymentManagement.tsx
  src/components/projects/StageCard.tsx
  src/pages/admin/DataManagement.tsx
  src/pages/user/projects/CreateRequest.tsx
  src/pages/user/projects/RequestDetail.tsx
Labels: 🔧 Refactor

#180 [Fix] 프로젝트 관련 오류 해결
  src/api/auth.ts
  src/components/projects/CreateProjectSteps.tsx
  src/components/projects/ProjectHeader.tsx
  src/pages/admin/projects/Project.tsx
  src/pages/user/MyArticles.tsx
  src/pages/user/UserDashboard.tsx
Labels: 🐞 Bugfix

#184 [Design] 로그인 화면 디자인 개선
  .tsconfig.tsbuildinfo
  src/pages/auth/Login.tsx
  src/pages/user/projects/ReapplyRequest.tsx
Labels: 💠 Styles

#187 [Design] 프로젝트 관련 디자인 수정
  src/components/projects/PaymentManagement.tsx
  src/components/projects/ProjectArticle.tsx
  src/components/projects/ProjectHeader.tsx
  src/services/projectService.ts
Labels: ✨ Feature

#189 [Design] 깃허브박스 링크 연결 및 로그인버튼 색깔 변경
  .tsconfig.tsbuildinfo
  src/pages/auth/Login.tsx
Labels: 💠 Styles
